# SpringBoot内嵌web容器配置
server:
  # SpringBoot内嵌web容器http端口号
  port: 2333
  # SpringBoot内嵌tomcat配置
  tomcat:
    # uri编码
    uri-encoding: UTF-8
    # 连接建立超时时间（单位：ms）
    connection-timeout: 12000
    # 最大等待队列长度：每个请求使用一个线程，线程数超过最大链接数后请求会进入等待队列，直到有线程处理
    accept-count: 1000
    # 线程数设置
    threads:
      # 最小线程数：SpringBoot启动时初始化的线程数量
      min-spare: 100
      # 最大线程数：可以设为CPU线程数的200~250倍
      max: 500
    # 最大连接数：Tomcat同一时间能接受的最大线程数量，需要大等于 max-threads + accept-count
    max-connections: 1500
  # 编码配置（编码过滤器）
  servlet:
    encoding:
      charset: UTF-8
      force-request: true
      force-response: true
      enabled: true

# Spring配置
spring:
  profiles:
    active: dev
  # thymeleaf配置
  thymeleaf:
    mode: HTML
    encoding: UTF-8
    cache: false
  # session存储方式
  session:
    store-type: redis

# mybatis plus配置
mybatis-plus:
  mapper-locations: classpath:org/elianacc/yurayura/dao/**/*.xml

# SpringBoot指标监控配置
management:
  endpoints:
    # 是否开启所有监控端点
    enabled-by-default: false
    # 以web方式暴露所有监控端点
    web:
      exposure:
        include: '*'
  endpoint:
    # 健康状况端点
    health:
      enabled: true
      show-details: always
    # SpringBean端点
    beans:
      enabled: true
    # 环境端点
    env:
      enabled: true
    # 应用信息端点
    info:
      enabled: true
    # 日志信息端点
    loggers:
      enabled: true
    # 指标信息端点
    metrics:
      enabled: true
